version: '3.8'
services:
  db:
    image: kartoza/postgis:12.0
    restart: always
    environment:
      - POSTGRES_USER=lousa1
      - POSTGRES_PASSWORD=!!Lousa1
      - POSTGRES_DB=lousa_test
    volumes:
      - postgres_lousa_test:/var/lib/postgresql/data
    ports:
      - '3434:5432'
volumes:
  postgres_lousa_test:
